-- H2 2.2.224;
;             
CREATE USER IF NOT EXISTS "SA" SALT 'cc9fa56eab94c73d' HASH 'c99ad52a3f9cfafecce6ad7d19d9c837909b6efe89b68730a7cf22eeea4ccfbe' ADMIN;         
CREATE MEMORY TABLE "PUBLIC"."PRODUCT"(
    "PRICE" FLOAT(53),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 6) NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);    
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");      
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT; 
INSERT INTO "PUBLIC"."PRODUCT" VALUES
(150000.0, 1, U&'Egy er\0151teljes laptop, ide\00e1lis munk\00e1ra \00e9s j\00e1t\00e9kra.', 'Laptop'),
(79990.0, 2, U&'Modern okostelefon, gyors teljes\00edtm\00e9ny \00e9s sz\00e9p kijelz\0151.', 'Okostelefon'),
(14990.0, 3, U&'Kiv\00e1l\00f3 hangmin\0151s\00e9g \00e9s k\00e9nyelmes viselet.', U&'Fejhallgat\00f3'),
(29990.0, 4, U&'Kompakt \00e9s k\00f6nny\0171 tablet, t\00f6k\00e9letes sz\00f3rakoz\00e1shoz \00e9s munk\00e1hoz.', 'Tablet'),
(4990.0, 5, U&'Tart\00f3s USB-C k\00e1bel, gyors adat\00e1tvitel.', U&'K\00e1bel'); 
